<?php

/**
 * @file
 * Provides a recitation entity type.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Render\Element;
use Drupal\piv_contest_recitation\Entity\Recitation;

/**
 * Implements hook_theme().
 */
function piv_contest_recitation_theme() {
  return [
    'recitation' => [
      'render element' => 'elements',
    ],
    'multiple_recitations_form_table_row' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for recitation templates.
 *
 * Default template: recitation.html.twig.
 */
function template_preprocess_recitation(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_inline_entity_form_table_fields_alter().
 */
function piv_contest_recitation_inline_entity_form_table_fields_alter(array &$fields, array $context) {
  if ($context['entity_type'] === 'recitation') {
    $fields['label'] = [
      'type' => 'callback',
      'label' => t('Poem'),
      'callback' => 'piv_contest_recitation_inline_entity_form_title_callback',
    ];
    $fields['language'] = [
      'type' => 'callback',
      'label' => t('Language'),
      'callback' => 'piv_contest_recitation_inline_entity_form_language_callback',
    ];
  }
}

/**
 * Custom callback.
 */
function piv_contest_recitation_inline_entity_form_language_callback(Recitation $entity) {
  return $entity->language()->getName();
}

/**
 * Custom callback.
 */
function piv_contest_recitation_inline_entity_form_title_callback(Recitation $entity) {
  /** @var \Drupal\node\Entity\Node $poem */
  $poem = $entity->field_poem->entity;
  if ($poem) {
    return $poem->getTitle();
  }

  return "";
}

/**
 * Implements hook_entity_presave().
 */
function piv_contest_recitation_recitation_presave(EntityInterface $entity) {
  if (!$entity->getTitle() && $entity->field_poem->entity) {
    $entity->setTitle($entity->field_poem->entity->getTitle());
  }
}

/**
 * Implements hook_ENTITY_TYPE_create().
 */
function piv_contest_recitation_recitation_create(EntityInterface $entity) {
  // Create a empty media on recitations so the field is already open when
  // creating a new recitation.
  $media = \Drupal::entityTypeManager()->getStorage('media')->create([
    'bundle' => 'remote_video',
  ]);
  $entity->field_recitation_video[] = $media;
}

/**
 * Implements template_preprocess_HOOK().
 */
function template_preprocess_multiple_recitations_form_table_row(&$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_views_query_alter().
 */
function piv_contest_recitation_views_query_alter($view, $query) {
  // The arguments for this views have spaces and slashes, a "or" argument for
  // views needs a + sign, a + sign is also a space in a urlencoded argument
  // which makes it hard to filter by arguments with space, slash is actually a
  // separator for arguments.
  // Manually transform the query condition into a "IN" condition.
  if ($view->id() == 'language_restricted_poems') {
    foreach ($query->where as &$where) {
      foreach ($where as &$conditions) {
        if (is_array($conditions)) {
          foreach ($conditions as &$condition) {
            if ($condition['field'] == 'node__field_grades.field_grades_value' && !empty($condition['value']) && is_string($condition['value'])) {
              $condition['operator'] = 'in';
              $condition['value'] = explode('+', $condition['value']);
            }
          }
        }
      }
    }
  }
}
