<?php

/**
 * @file
 * Primary module hooks for PIV Constest module.
 */

use Drupal\Core\Render\Element;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Component\Serialization\Json;
use Drupal\piv_contest_competition_entry\Form\CompetitionEntryForm;

/**
 * Get a student name from a recitation or a competition entry.
 */
function piv_contest_get_student_name($entity) {
  $student_name = $entity->field_student_stage_name->value;
  if (!empty($student_name)) {
    return $student_name;
  }
  $first_name = $entity->field_student_name->value;
  $last_name = $entity->field_student_last_name->value;
  return "{$first_name} {$last_name}";
}

/**
 * Implements hook_entity_type_alter().
 */
function piv_contest_entity_type_alter(array &$entity_types) {
  if (!empty($entity_types['paragraph'])) {
    $entity_types['paragraph']->addConstraint('stream_constraint');
  }
}

/**
 * Implements hook_theme().
 */
function piv_contest_theme() {
  return [
    'recitation_score_form_default' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Implements template_preprocess_HOOK().
 */
function template_preprocess_recitation_score_form_default(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['form'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_theme_suggestions_alter().
 */
function piv_contest_theme_suggestions_alter(array &$suggestions, array $variables, $hook) {
  if (in_array($hook, [
    'competition',
    'competition_entry',
    'judging_session',
    'recitation',
    'score',
    'score_template',
  ])) {
    $view_mode = $variables['elements']['#view_mode'] ?? NULL;
    if ($view_mode) {
      $suggestions[] = "{$hook}__{$view_mode}";
    }
  }
}

/**
 * @defgroup piv_contest_entity_access Custom entity access
 * @{
 * Custom access to custom entities.
 *
 * The code here prevent inconsistences by preventing users from deleting
 * content that is being referenced by other content.
 * For example: deleting a score_template when there is a score referencing it.
 * Further validation are created as constraints.
 *
 * @see \Drupal\piv_contest_score_template\Plugin\Validation\Constraint\ScoreTemplateConstraintValidator::validate()
 * @see \Drupal\piv_contest\Plugin\Validation\Constraint\CompetitionConstraintValidator::validate()
 */

/**
 * Custom function to verify if there are scores for a score_template_type.
 */
function _piv_contest_score_exists_for_score_template_type($bundle) {
  return (bool) \Drupal::entityTypeManager()->getStorage('score')->getQuery()
    ->accessCheck(FALSE)
    ->condition('score_template.entity:score_template.bundle', $bundle)
    ->execute();
}

/**
 * Implements hook_ENTITY_TYPE_access().
 *
 * Prevents deleting score_template entities if there is a score referencing it.
 */
function piv_contest_score_template_access(EntityInterface $entity, $operation, AccountInterface $account) {
  if ($operation == 'delete') {
    $query = \Drupal::entityTypeManager()
      ->getStorage('score')
      ->getQuery()
      ->accessCheck(FALSE);
    $results = $query->condition('score_template', $entity->id())->execute();
    if ($results) {
      return AccessResult::forbidden();
    }
  }
  return AccessResult::neutral();
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Prevent editing some fields in a score template if there are scores using it
 * already.
 */
function piv_contest_form_score_template_default_edit_form_alter(&$form, FormStateInterface $form_state) {
  if (_piv_contest_score_exists_for_score_template_type('default')) {
    \Drupal::messenger()->addWarning('This score_template has score entities referencing it. Some fields are disabled.');
    // Disable everything but the label.
    $form['field_criteria']['widget']['#disabled'] = TRUE;
    foreach (Element::children($form['field_criteria']['widget']) as $delta) {
      $field_criteria = &$form['field_criteria']['widget'][$delta];
      $field_criteria['subform']['field_criterion']['#disabled'] = FALSE;
    }
    // Let change the score options labels, but can't add more or delete.
    foreach (Element::children($form['field_score_option_labels']['widget']) as $delta) {
      $field_score_option_labels = &$form['field_score_option_labels']['widget'][$delta]['value'];
      if ($field_score_option_labels['#default_value']) {
        $field_score_option_labels['#required'] = TRUE;
      }
      else {
        $field_score_option_labels['#disabled'] = TRUE;
      }
    }
    $form['field_score_option_labels']['widget']['add_more']['#disabled'] = TRUE;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Make it impossible to change the "Score Type" when editing a
 * score_template_type if there are score entities referencing score_template
 * entities of this bundle.
 */
function piv_contest_form_score_template_type_edit_form_alter(&$form, FormStateInterface $form_state) {
  $id = $form_state->getFormObject()->getEntity()->id();
  if (_piv_contest_score_exists_for_score_template_type($id)) {
    $form['score_type']['#disabled'] = TRUE;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function piv_contest_form_competition_default_edit_form_alter(&$form, FormStateInterface $form_state) {
  // There is also a constraint with the same conditions.
  // @see \Drupal\piv_contest\Plugin\Validation\Constraint\CompetitionConstraintValidator::validate()
  $competition = $form_state->getFormObject()->getEntity();
  $results = \Drupal::entityTypeManager()->getStorage('score')->getQuery()
    ->accessCheck(FALSE)
    ->condition('judging_session.entity:judging_session.field_competition', $competition->id())
    ->execute();
  if ($results) {
    $form['field_score_template']['#disabled'] = TRUE;
    \Drupal::messenger()->addWarning('This competition already has recitations and/or scores, some fields are disabled.');
  }
}

/**
 * Implements hook_ENTITY_TYPE_access().
 */
function piv_contest_score_template_type_access(EntityInterface $entity, $operation, AccountInterface $account) {
  $id = $entity->id();
  if ($operation == 'delete' && _piv_contest_score_exists_for_score_template_type($id)) {
    \Drupal::messenger()->addWarning('This score_template_type has score entities referencing it. Deleting and editing are disabled.');
    return AccessResult::forbidden();
  }
  return AccessResult::neutral();
}

/**
 * Implements hook_ENTITY_TYPE_access().
 */
function piv_contest_field_config_access(EntityInterface $entity, $operation, AccountInterface $account) {
  if ($operation == 'delete' && $entity->get('entity_type') == 'score_template') {
    if (_piv_contest_score_exists_for_score_template_type($entity->get('bundle'))) {
      // Duplicated messages are not displayed duplicated.
      \Drupal::messenger()->addWarning('This score_template_type has score entities referencing it. Deleting fields is disabled.');
      return AccessResult::forbidden();
    }
  }
  return AccessResult::neutral();
}

/**
 * @} End of "defgroup piv_contest_entity_access".
 */

/**
 * Implements hook_field_widget_WIDGET_TYPE_form_alter().
 */
function piv_contest_field_widget_options_select_form_alter(&$element, FormStateInterface $form_state, $context) {
  $form_object = $form_state->getFormObject();
  // Filter the grades select element by the allowed values in the competition.
  if (is_a($form_object, CompetitionEntryForm::class) && $context['items']->getName() == 'field_student_grade') {
    $competition_entry = $form_object->getEntity();
    if ($competition = $competition_entry->field_competition->entity) {
      $allowed_values = array_flip(array_column($competition->field_allowed_grades->getValue(), 'value'));
      if ($allowed_values) {
        $element['#options'] = array_intersect_key($element['#options'], $allowed_values);
      }
    }
  }
}

/**
 * @defgroup piv_contest_delete Delete dependent entities
 * @{
 * Make sure children entities are deleted when parents are deleted.
 */

/**
 * Implements hook_ENTITY_TYPE_delete().
 *
 * Delete referenced recitations when deleting the competition entry.
 */
function piv_contest_competition_entry_delete(EntityInterface $entity) {
  foreach ($entity->field_recitations->referencedEntities() as $recitation) {
    $recitation->delete();
  }
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 *
 * Delete referenced medias when deleting a recitation.
 */
function piv_contest_recitation_delete(EntityInterface $entity) {
  foreach ($entity->field_recitation_video->referencedEntities() as $media) {
    $media->delete();
  }
}

/**
 * @} End of "defgroup piv_contest_delete".
 */

/**
 * Implements hook_form_FORM_BASE_alter().
 */
function piv_contest_form_competition_entry_form_alter(&$form, FormStateInterface $form_state) {
  if ($form_state->get('piv_custom_weight')) {
    $form['recitation_weight'] = [
      '#type' => 'textfield',
      '#name' => 'recitation_weight',
      '#attributes' => ['class' => ['hidden']],
      '#maxlength' => 9999999,
    ];
    array_unshift($form['actions']['submit']['#submit'], 'piv_contest_competition_entry_custom_submit');
  }
}

/**
 * Custom submit.
 *
 * A custom field "recitation_weight" copies the values from the recitation form
 * for the recitations weight. This is required because the form that reorder
 * the recitations is not the same form that edits the competition entry.
 */
function piv_contest_competition_entry_custom_submit(&$form, FormStateInterface $form_state) {
  $input = $form_state->getUserInput();
  $weights = Json::decode($input['recitation_weight'] ?? []);
  if ($weights) {
    $entity = $form_state->getFormObject()->getEntity();
    $ids = array_column($entity->field_recitations->getValue(), 'target_id');
    $order = [];
    foreach ($weights as $name => $weight) {
      $weight_delta = explode('[', $name)[1] ?? '';
      $weight_delta = str_replace(']', '', $weight_delta);
      if (is_numeric($weight_delta)) {
        $order[$weight] = $ids[$weight_delta];
      }
    }
    $order = array_filter($order);
    if (count($ids) == count(array_intersect($order, $ids))) {
      ksort($order);
      $entity->field_recitations = $order;
    }
  }
}

/**
 * Implements hook_entity_presave().
 */
function piv_contest_paragraph_presave(EntityInterface $entity) {
  // Paragraphs have a reference to their parent entities that holds the parent
  // id, type and field name that are referencing it. The parent is set on a
  // postSave hook and is updated to the last entity that was saved, this is
  // done on Drupal\entity_reference_revisions\Plugin\Field\FieldType::EntityReferenceRevisionsItem().
  // The competition_stream paragraph is used on competitions and also
  // referenced in a competition_entry when creating one, that means that if a
  // user creates a competition_entry, this stream paragraph will now set the
  // competition entry as the parent.
  // Now, if a user deletes that competition entry, the paragraph will be set
  // as orphan and will get deleted on cron by the entity_reference_revisions
  // module.
  // This hook prevents the parent from being updated in the cases mentioned
  // above, guaranting that a competition is always the parent.
  if ($entity->bundle() == 'competition_stream') {
    if ($entity->parent_type->value != 'competition' && $entity->original) {
      $original = $entity->original;
      if ($original->parent_type->value == 'competition') {
        $entity->parent_id = $original->parent_id;
        $entity->parent_type = $original->parent_type;
        $entity->parent_field_name = $original->parent_field_name;
      }
    }
  }

}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function piv_contest_form_editablefields_form_alter(&$form, $form_state, $form_id) {
  if (!empty($form['submit']['#ajax'])) {
    $form['submit']['#ajax']['disable-refocus'] = TRUE;
  }
}

/**
 * Check if school is excluded from contests.
 *
 * @see /admin/contest/contest-settings
 */
function piv_contest_school_is_excluded($school_id) {
  if (!is_numeric($school_id)) {
    return FALSE;
  }

  $config = config_pages_config('contest_settings');
  if (!$config) {
    return FALSE;
  }

  $schools = array_column($config->field_excluded_schools->getValue(), 'target_id');
  return in_array($school_id, $schools);
}

/**
 * Helper function to hide fields on score entities.
 */
function _piv_contest_hide_score_fields(&$form, $bundle) {
  if (in_array($bundle, ['live_competition', 'accuracy_live_competition'])) {
    $form['judging_session']['#access'] = FALSE;
    $form['recitation']['#access'] = FALSE;
  }
  if ($bundle == 'accuracy_live_competition') {
    $form['score_template']['#access'] = FALSE;
  }
}

/**
 * Implements hook_inline_entity_form_entity_form_alter().
 */
function piv_contest_inline_entity_form_entity_form_alter(array &$entity_form, FormStateInterface &$form_state) {
  if ($entity_form['#entity_type'] == 'score') {
    _piv_contest_hide_score_fields($entity_form, $entity_form['#bundle']);
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function piv_contest_form_score_form_alter(&$form, FormStateInterface $form_state) {
  $bundle = $form_state->getFormObject()->getEntity()->bundle();
  _piv_contest_hide_score_fields($form, $bundle);
}

/**
 * Implements hook_ENTITY_TYPE_prepare_form().
 */
function piv_contest_competition_prepare_form(EntityInterface $entity, $operation, FormStateInterface $form_state) : void {
  if ($entity->bundle() != 'default') {
    return;
  }

  // Synchronize the count of competition notification level paragraphs
  // on form edit. This creates new empty paragraphs but doesn't delete
  // if there are more notification paragraphs than competition levels.
  // Instead it will display a warning.
  $count_diff = count($entity->field_competition_levels) - count($entity->field_notification_levels);
  if ($count_diff > 0) {
    $paragraph_storage = \Drupal::entityTypeManager()->getStorage('paragraph');
    while ($count_diff-- > 0) {
      $entity->field_notification_levels[] = $paragraph_storage->create([
        'type' => 'competition_notification_level',
      ]);
    }
  }
  elseif ($count_diff < 0) {
    \Drupal::messenger()->addWarning(t(
      'Note that there are more notifications levels (Notifications tab) than levels (@levels) in this competition.',
      ['@levels' => implode(', ', array_column($entity->field_competition_levels->getValue(), 'value'))],
    ));
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function piv_contest_form_competition_form_alter(&$form, FormStateInterface $form_state) {
  $form['#attached']['library'][] = 'piv_contest/competition-notifications';
  array_unshift($form['actions']['submit']['#submit'], '_piv_contest_populate_rank_deltas');
}

/**
 * Populate field_rank on competition_notification_rank paragraphs.
 */
function _piv_contest_populate_rank_deltas(array &$form, FormStateInterface $form_state): void {
  $levels = $form_state->getValue('field_notification_levels') ?? [];
  foreach ($levels as &$level) {
    if (empty($level['subform']['field_ranks'])) {
      continue;
    }
    foreach ($level['subform']['field_ranks'] as $rank_delta => &$rank) {
      if (!is_numeric($rank_delta) || empty($rank['subform'])) {
        continue;
      }
      $rank['subform']['field_rank'][0]['value'] = ($rank_delta + 1);
    }
  }
  $form_state->setValue('field_notification_levels', $levels);
}

/**
 * Implements hook_field_widget_complete_form_alter().
 */
function piv_contest_field_widget_complete_form_alter(&$element, FormStateInterface $form_state, $context) {
  if (!empty($element['widget']['#field_name']) && $element['widget']['#field_name'] == 'field_notification_levels') {
    foreach (Element::children($element['widget']) as $delta) {
      // Add a class to a container to use it as the wrapper for our
      // labels, which are controlled by js.
      if (!empty($element['widget'][$delta]['top']['type'])) {
        $element['widget'][$delta]['top']['type']['#attributes']['class'][] = 'js-notification-label';
        $element['widget'][$delta]['top']['type']['#attributes']['class'][] = 'notification-label';
      }
    }
  }
}

/**
 * Implements hook_preprocess_field_multiple_value_form().
 *
 * Remove the tabledrag functionality from some fields.
 */
function piv_contest_preprocess_field_multiple_value_form(&$variables) {
  $field_name = $variables['element']['#field_name'] ?? '';
  if (in_array($field_name, ['field_competition_levels', 'field_notification_levels', 'field_tokens'])) {
    $variables['table']['#attributes']['class'] = ['drag-removed'];
    unset($variables['table']['#tabledrag']);
    unset($variables['table']['#header'][2]);
    foreach ($variables['table']['#rows'] as $delta => $row) {
      unset($variables['table']['#rows'][$delta]['class']);
      unset($variables['table']['#rows'][$delta]['data'][3]);
    }
  }
}
