stages:
  - deploy

deploy:
 stage: deploy
 script:
   - /usr/bin/cd /var/www/dev.poetryinvoice.com
   - /usr/bin/git pull
   - /usr/bin/composer install
   - /var/www/dev.poetryinvoice.com/vendor/drush/drush/drush -y cache-rebuild
   - /var/www/dev.poetryinvoice.com/vendor/drush/drush/drush -y updatedb
   - /var/www/dev.poetryinvoice.com/vendor/drush/drush/drush -y config-import
 only:
   - dev
