piv_contest_competition.competition_type.*:
  type: config_entity
  label: 'Competition type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
