<?php

/**
 * The PIV Field module.
 */

use Drupal\Core\Form\FormStateInterface;

function piv_field_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'user_teacher_edit_form') {
    $isPostalCode = 0;
    if ($form_state->getValue('pcode')) {
      $isPostalCode = 1;
    }

    // Hide the Drupal original field. It will be populated from the custom field bellow.
    $form['field_school']['#access'] = FALSE;
    $default_value = $form['field_school']['widget'][0]['target_id']['#default_value'];

    // Custom submit.
    $form['actions']['submit']['#submit'][] = 'piv_field_teacher_edit_form_submit';

    // Custom School fields.
    $form['school'] = [
      '#title' => t('School'),
      '#description' => t('Type a few letters of your school name, wait, and then select it from the list. All Canadian schools should be in our system.'),
      '#type' => 'entity_autocomplete',
      '#target_type' => 'node',
      '#default_value' => $default_value,
      "#validate_reference" => false,
      '#selection_handler' => 'default:piv_school',
      '#selection_settings' => [
        'target_bundles' => [
          "school" => "school",
        ],
        'sort' => [
          "field" => "_none",
          "direction" => "ASC",
        ],
        "postal_code" => $isPostalCode,
        "auto_create" => 0,
        "auto_create_bundle" => "",
        "match_operator" => "CONTAINS",
        "match_limit" => 10,
      ],
      '#required' => TRUE,
      '#weight' => 8,
      "#prefix" => "<div id='school-reference-wrapper'>",
      "#suffix" => "</div>",
    ];

    $form['pcode'] = [
      '#title' => t('Search by postal code instead'),
      '#type' => 'checkbox',
      '#description' => t('Check this option, and then type your school\'s postal code in the School field above.'),
      '#default_value' => 0,
      '#ajax' => [
        'callback' => 'piv_field_postal_code_callback',
        'event' => 'change',
        'wrapper' => 'school-reference-wrapper',
      ],
      '#weight' => 9,
    ];
  }
}

function piv_field_postal_code_callback(array &$form, FormStateInterface $form_state) {
  $form_state->setRebuild();
  return $form['school'];
}

/**
 * Custom form submit for Teacher User form.
 */
function piv_field_teacher_edit_form_submit(array &$form, FormStateInterface $form_state) {
  $school_id = $form_state->getValue('school');
  if ($school_id) {
    $account = $form_state->getFormObject()->getEntity();
    $value = [
      ['target_id' => $school_id],
    ];
    $account->set('field_school', $value);
    $account->save();
  }
}
