<?php

/**
 * @file
 * Provides a score template entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function piv_contest_score_template_theme() {
  return [
    'score_template' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for score template templates.
 *
 * Default template: score-template.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the score template information
 *     and any fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_score_template(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
