piv_contest_score_template.score_template_type.*:
  type: config_entity
  label: 'Score Template type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
