<?php

/**
 * @file
 * Provides a competition entry entity type.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function piv_contest_competition_entry_theme() {
  return [
    'competition_entry' => [
      'render element' => 'elements',
    ],
  ];
}

function piv_contest_competition_entry_competition_entry_presave(EntityInterface $entity) {
  /** @var \Drupal\piv_contest\CompetitionEnrollment $competition_enrollment_service */
  $competition_enrollment_service = \Drupal::service('piv_contest.competition_enrollment');

  $number_valid_recitations = $competition_enrollment_service->getNumberOfValidRecitationsInEntry($entity);

  $competition = $entity->field_competition->entity;
  foreach ($competition->field_competition_streams as $stream_field) {
    if ($stream_field->target_id === $entity->field_stream->target_id) {
      $required_recitations_stream = $competition_enrollment_service->getRequiredRecitationsForStream($stream_field->entity);
      if ($number_valid_recitations >= $required_recitations_stream && $entity->field_release_form->entity != NULL) {
        $entity->field_complete = TRUE;
      }
    }
  }
}

function piv_contest_form_alter(&$form, FormStateInterface $formState, $form_id) {
  if ($form_id != 'competition_entry_default_teacher_competition_entry_form') {
    return;
  }

  $competition_entry = \Drupal::routeMatch()->getParameter('competition_entry');
  if (!$competition_entry) {
    return;
  }

  /** @var \Drupal\piv_contest_competition_entry\Service\CompetitionLockService $lock_service */
  $lock_service = \Drupal::service('piv_contest_competition_entry.competition_lock_service');
  if ($lock_service->isLocked($competition_entry)) {
    $form['#disabled'] = true;
  }
}

/**
 * Prepares variables for competition entry templates.
 *
 * Default template: competition-entry.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the competition entry information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_competition_entry(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
