<?php

/**
 * @file
 * Provides a competition entry entity type.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;
use Drupal\piv_contest_competition_entry\Entity\CompetitionEntry;
use Drupal\user\Entity\User;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_theme().
 */
function piv_contest_competition_entry_theme() {
  return [
    'competition_entry' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function piv_contest_competition_entry_competition_entry_presave(EntityInterface $entity) {
  /** @var \Drupal\piv_contest\CompetitionEnrollment $competition_enrollment_service */
  $competition_enrollment_service = \Drupal::service('piv_contest.competition_enrollment');

  $current_user = \Drupal::currentUser();
  $user = User::load($current_user->id());
  $competition = $entity->field_competition->entity;
  /** @var \Drupal\node\NodeInterface $school */
  $school = $user->field_school->entity;

  $entity->field_complete = FALSE;
  if ($competition_enrollment_service->isCompetitionEntryCompleted($entity)) {
    $entity->field_complete = TRUE;
  }

  $stream = $entity->getStream();
  if ($stream) {
    // Set default title if title is empty.
    // Set default title.
    $title = $entity->getTitle();
    if (!$title && $school) {
      $entity->setTitle(
        sprintf('%s - %s - %s',
        $school->label(),
        $competition->getTitle(),
        $stream->field_label->value,
      ));
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function piv_contest_competition_entry_form_alter(&$form, FormStateInterface $formState, $form_id) {
  if ($form_id != 'competition_entry_default_teacher_competition_entry_form') {
    return;
  }

  $competition_entry = \Drupal::routeMatch()->getParameter('competition_entry');
  if (!$competition_entry) {
    return;
  }

  /** @var \Drupal\piv_contest_competition_entry\Service\CompetitionLockService $lock_service */
  $lock_service = \Drupal::service('piv_contest_competition_entry.competition_lock_service');
  if ($lock_service->isLocked($competition_entry)) {
    $form['#disabled'] = TRUE;
  }
}

/**
 * Prepares variables for competition entry templates.
 *
 * Default template: competition-entry.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the competition entry
 *     information and any fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_competition_entry(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
