piv_futureverse.futureverse_application_type.*:
  type: config_entity
  label: 'Futureverse Application type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
