<?php

/**
 * @file
 * Primary module hooks for PIV Poem Password module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Render\Element;

/**
 * Implements hook_ENTITY_TYPE_view_alter().
 */
function piv_poem_password_node_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  if ($entity->hasField('field_password_protected') && $display->getOriginalMode() == 'full') {
    if (empty($entity->field_password_protected->value)) {
      // Not password protected.
      return;
    }

    $current_user = \Drupal::currentUser();
    if ($current_user->hasPermission('bypass poem password')) {
      // User can bypass.
      return;
    }
    $cookie = \Drupal::request()->cookies
      ->get('Drupal_visitor_piv_poem_password_valid') ?? '';
    $session = \Drupal::service('tempstore.private')
      ->get('piv_poem_password')->get('piv_poem_password_valid');
    if (!$cookie && $session) {
      user_cookie_save(['piv_poem_password_valid' => 1]);
    }

    if ($cookie || $session) {
      // User already entered password.
      return;
    }

    // Hide all renderable elements.
    foreach (Element::children($build) as $key) {
      $build[$key]['#access'] = FALSE;
    }
    $build['piv_poem_password_form'] = \Drupal::formBuilder()
      ->getForm('Drupal\piv_poem_password\Form\PasswordForm');
    $build['#cache']['contexts'][] = 'cookies:Drupal_visitor_piv_poem_password_valid';
  }
}
