<?php

/**
 * @file
 * Functions to support theming in the SASS Starterkit subtheme.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;

/**
 * Implements hook_form_system_theme_settings_alter() for settings form.
 *
 * Replace Barrio setting options with subtheme ones.
 *
 * Example on how to alter theme settings form
 */
function lvp_barrio_form_system_theme_settings_alter(&$form, FormStateInterface $form_state) {
  $form['components']['navbar']['bootstrap_barrio_navbar_top_background']['#options'] = [
    'bg-primary' => t('Primary'),
    'bg-secondary' => t('Secondary'),
    'bg-light' => t('Light'),
    'bg-dark' => t('Dark'),
    'bg-white' => t('White'),
    'bg-transparent' => t('Transparent'),
  ];
  $form['components']['navbar']['bootstrap_barrio_navbar_background']['#options'] = [
    'bg-primary' => t('Primary'),
    'bg-secondary' => t('Secondary'),
    'bg-light' => t('Light'),
    'bg-dark' => t('Dark'),
    'bg-white' => t('White'),
    'bg-transparent' => t('Transparent'),
  ];
}

/**
 * Make language variable available in twig files
 */
function lvp_barrio_preprocess_block(&$vars) {

  $language = \Drupal::languageManager()->getCurrentLanguage()->getId();
  $vars['language'] = $language;
}

/**
 * Use language code for the language switcher
 */
function lvp_barrio_preprocess_links__language_block(&$variables) {
  foreach ($variables['links'] as $i => $link) {
    // @var \Drupal\language\Entity\ConfigurableLanguage $linkLanguage
    $linkLanguage = $link['link']['#options']['language'];
    $variables['links'][$i]['link']['#title'] = $linkLanguage->get('id');
  }
}


function lvp_barrio_preprocess_page(&$variables) {
  switch (theme_get_setting('bootstrap_barrio_navbar_offcanvas')) {
    case 'offcanvas-collapse':
      $variables['navbar_offcanvas'] = TRUE;
      $variables['navbar_collapse_class'] = "offcanvas offcanvas-top";
      $variables['navbar_collapse_btn_data'] = "offcanvas";
      break;
    default:
      $variables['navbar_offcanvas'] = TRUE;
      $variables['navbar_collapse_class'] = 'collapse navbar-collapse justify-content-end';
      $variables['navbar_collapse_btn_data'] = "collapse";
  }

  $variables['page']['header']['#sorted'] = FALSE;
  $weight = $variables['page']['header']['usericonheader']['#weight'] ?? -14;
  $url = Url::fromRoute('view.search.page')->toString();
  $variables['page']['header']['search_icon'] = [
    '#markup' => "<a href='{$url}' class='search-icon'><svg width='24' height='24' fill='#fff' xmlns='http://www.w3.org/2000/svg' fill-rule='evenodd' clip-rule='evenodd'><path d='M15.853 16.56c-1.683 1.517-3.911 2.44-6.353 2.44-5.243 0-9.5-4.257-9.5-9.5s4.257-9.5 9.5-9.5 9.5 4.257 9.5 9.5c0 2.442-.923 4.67-2.44 6.353l7.44 7.44-.707.707-7.44-7.44zm-6.353-15.56c4.691 0 8.5 3.809 8.5 8.5s-3.809 8.5-8.5 8.5-8.5-3.809-8.5-8.5 3.809-8.5 8.5-8.5z'/></svg></a>",
    '#weight' => $weight - 0.1,
    '#allowed_tags' => ['svg', 'path', 'a'],
  ];
}

  /**
  * Implements hook_preprocess_page() for page.html.twig.
  */
  function lvp_barrio_preprocess_page__front(array &$variables) {
    $variables['slideshow'] = views_embed_view('home_page_slider_fca', 'block_1');
    $variables['flyingblocks1'] = views_embed_view('home_page_slider_fca', 'block_2');
    $variables['flyingblocks2'] = views_embed_view('home_page_slider_fca', 'block_3');
    $variables['flyingblocks3'] = views_embed_view('home_page_slider_fca', 'block_4');
    $variables['flyingblocks4'] = views_embed_view('home_page_slider_fca', 'block_5');
  }

