<?php

/**
 * @file
 * Provides a competition entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function piv_contest_competition_theme() {
  return [
    'competition' => [
      'render element' => 'elements',
    ],
    // UI to let teachers manage their school's enrollement in a competition.
    'competition_enrollement_progress' => [
      'variables' => [
        'competition' => NULL,
        'teacher' => NULL,
        'school' => NULL,
        'streams' => [],
        'message' => [],
        'competition_has_criteria' => FALSE,
      ],
    ],
  ];
}

/**
 * Prepares variables for competition templates.
 *
 * Default template: competition.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the competition information and
 *     any fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_competition(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements template_preprocess_competition_enrollement_progress()
 */
function template_preprocess_competition_enrollement_progress(&$variables) {
  /** @var \Drupal\piv_contest\CompetitionEnrollment $enrollment */
  $enrollment = Drupal::service('piv_contest.competition_enrollment');
  $enrollment->init(
    $variables['school'],
    $variables['competition'],
    $variables['teacher']
  );
  $variables['streams'] = $enrollment->getStreams();
  $variables['competition_has_criteria'] = $enrollment->competitionHasRequiredCriteria($variables['competition']);
}

/**
 * Implements hook_form_BASE_FORM_alter().
 */
function piv_contest_competition_form_competition_form_alter(&$form, FormStateInterface $form_state) {
  // It is possible to add #required with #states, however it doesn't work well
  // for address and only 1 school is required on the invited schools field.
  // Instead, verify in a custom validation.
  $form['field_location']['#states'] = [
    'visible' => [
      ':input[name="field_online_competition[value]"]' => ['checked' => FALSE],
    ],
  ];
  $form['field_invited_schools']['#states'] = [
    'visible' => [
      ':input[name="field_by_invitation_only[value]"]' => ['checked' => TRUE],
    ],
  ];
}
