<?php

/**
 * @file
 * Provides a competition entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function piv_contest_competition_theme() {
  return [
    'competition' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for competition templates.
 *
 * Default template: competition.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the competition information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_competition(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
