<?php

/**
 * @file
 * Provides a competition entry entity type.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_theme().
 */
function piv_contest_competition_entry_theme() {
  return [
    'competition_entry' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function piv_contest_competition_entry_competition_entry_presave(EntityInterface $entity) {
  $competition_enrollment_service = \Drupal::service('piv_contest.competition_enrollment');
  $competition = $entity->field_competition->entity;
  $school = $entity->field_school->entity;

  if ($competition_enrollment_service->isCompetitionEntryCompleted($entity)) {
    if (empty($entity->field_complete->value)) {
      // Competition was set to complete now.
      \Drupal::messenger()->addStatus(t('Your competition entry is complete!'));
    }
    $entity->field_complete = TRUE;
  }
  else {
    $entity->field_complete = FALSE;
  }

  $stream = $entity->getStream();
  // If there is no stream or no school do not update the title.
  if ($stream && $school) {
    $entity->setTitle(
      sprintf('%s - %s - %s',
      $school->label(),
      $competition->getTitle(),
      $stream->field_label->value,
    ));
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function piv_contest_competition_entry_form_competition_entry_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $competition_entry = $form_state->getFormObject()->getEntity();
  $lock_service = \Drupal::service('piv_contest_competition_entry.competition_lock_service');
  if ($lock_service->isLocked($competition_entry)) {
    $form['#disabled'] = TRUE;
    \Drupal::messenger()
      ->addWarning('This competition entry is locked. Only edit it if you know what you are doing.');
  }
}

/**
 * Prepares variables for competition entry templates.
 *
 * Default template: competition-entry.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the competition entry
 *     information and any fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_competition_entry(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_BASE_FORM_ID_alter().
 */
function piv_contest_competition_entry_form_competition_default_edit_form_alter(&$form, FormStateInterface $form_state) {
  // Disable stream fields if there is a competition entry referencing it.
  // Stream is a paragraph referenced in the field_competition_streams field.
  $storage = \Drupal::entityTypeManager()->getStorage('competition_entry');
  $entity = $form_state->getFormObject()->getEntity();
  if ($entity->isNew()) {
    return;
  }

  $fields_to_disable = [
    'field_min_recitations',
    'field_entries_required_school',
    'field_max_entries_school',
    'field_stream_languages',
  ];
  foreach ($entity->field_competition_streams as $key => $field_item) {
    $items = $storage->getQuery()
      ->condition('field_stream.target_id', $field_item->target_id)
      ->range(0, 1)
      ->execute();
    if (count($items)) {
      foreach ($fields_to_disable as $field_name) {
        $form['field_competition_streams']['widget'][$key]['subform'][$field_name]['#disabled'] = TRUE;
      }
    }
  }
}

/**
 * Implements hook_entity_bundle_field_info_alter().
 */
function piv_contest_competition_entry_entity_bundle_field_info_alter(&$fields, EntityTypeInterface $entity_type, $bundle) {
  if ($entity_type->id() == 'competition_entry' && !empty($fields['field_school'])) {
    $fields['field_school']->addConstraint('PivContestCompetitionEntrySchool');
  }
}
