<?php

/**
 * @file
 * Provides a competition entry entity type.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;
use Drupal\piv_contest_competition\Form\CompetitionForm;
use Drupal\user\Entity\User;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_theme().
 */
function piv_contest_competition_entry_theme() {
  return [
    'competition_entry' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function piv_contest_competition_entry_competition_entry_presave(EntityInterface $entity) {
  /** @var \Drupal\piv_contest\CompetitionEnrollment $competition_enrollment_service */
  $competition_enrollment_service = \Drupal::service('piv_contest.competition_enrollment');

  $current_user = \Drupal::currentUser();
  $user = User::load($current_user->id());
  $competition = $entity->field_competition->entity;
  /** @var \Drupal\node\NodeInterface $school */
  $school = $user->field_school->entity;

  $entity->field_complete = FALSE;
  if ($competition_enrollment_service->isCompetitionEntryCompleted($entity)) {
    $entity->field_complete = TRUE;
  }

  $stream = $entity->getStream();
  if ($stream) {
    // Set default title if title is empty.
    // Set default title.
    $title = $entity->getTitle();
    if (!$title && $school) {
      $entity->setTitle(
        sprintf('%s - %s - %s',
        $school->label(),
        $competition->getTitle(),
        $stream->field_label->value,
      ));
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function piv_contest_competition_entry_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (in_array($form_id, ['competition_entry_default_edit_form', 'competition_entry_default_teacher_competition_entry_form'])) {
    _piv_contest_competition_entry_form_show_locked_message();
  }

  if ($form_id != 'competition_entry_default_teacher_competition_entry_form') {
    return;
  }

  $competition_entry = \Drupal::routeMatch()->getParameter('competition_entry');
  if (!$competition_entry) {
    return;
  }

  /** @var \Drupal\piv_contest_competition_entry\Service\CompetitionLockService $lock_service */
  $lock_service = \Drupal::service('piv_contest_competition_entry.competition_lock_service');
  if ($lock_service->isLocked($competition_entry)) {
    $form['#disabled'] = TRUE;
  }

}

/**
 * Prepares variables for competition entry templates.
 *
 * Default template: competition-entry.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the competition entry
 *     information and any fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_competition_entry(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Competition Default Edit form Alter.
 */
function piv_contest_competition_entry_form_competition_default_edit_form_alter(&$form, FormStateInterface $form_state) {

  $storage = \Drupal::entityTypeManager()->getStorage('competition_entry');

  $build_info = $form_state->getBuildInfo();
  if (!isset($build_info['callback_object'])) {
    return;
  }

  $callback_object = $build_info['callback_object'];
  if (!$callback_object instanceof CompetitionForm) {
    return;
  }

  $entity = $callback_object->getEntity();

  $fields_to_disable = [
    'field_min_recitations',
    'field_entries_required_school',
    'field_max_entries_school',
    'field_stream_languages',
  ];

  foreach ($entity->field_competition_streams as $key => $field_item) {
    $items = $storage->getQuery()
      ->condition('field_stream.target_id', $field_item->target_id)
      ->range(0, 1)
      ->execute();

    $has_items = count($items) > 0;
    if ($has_items) {
      // Check if there is any competition entry for that competition.
      foreach ($fields_to_disable as $field_name) {
        $form['field_competition_streams']['widget'][$key]['subform'][$field_name]['#disabled'] = TRUE;
      }
    }
  }
}

function _piv_contest_competition_entry_form_show_locked_message() {
  $competition_entry = \Drupal::routeMatch()->getParameter('competition_entry');
  if (!$competition_entry) {
    return;
  }

  /** @var \Drupal\piv_contest_competition_entry\Service\CompetitionLockService $lock_service */
  $lock_service = \Drupal::service('piv_contest_competition_entry.competition_lock_service');
  if ($lock_service->isLocked($competition_entry)) {
    \Drupal::messenger()->addWarning('This competition entry is locked. Only edit it if you know what you are doing.');
  }
}
