<?php

/**
 * @file
 * Futureverse+ hooks and functionalities.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\piv_futureverse\JournalHelper;
use Drupal\Core\Url;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function piv_futureverse_form_journal_year_form_alter(array &$form, FormStateInterface $form_state) {
  $form['#attached']['library'][] = 'piv_futureverse/admin';
}

/**
 * Implements hook_entity_insert().
 */
function piv_futureverse_entity_insert(EntityInterface $entity) : void {
  if ($entity->getEntityTypeId() != 'node') {
    return;
  }

  if ($entity->bundle() != 'journal_poem') {
    return;
  }

  // Assign a journal poem to the current futureverse+ journal month if
  // one exists.
  $months = JournalHelper::getJournalMonths();
  if ($months) {
    $month = reset($months);
    $month->field_journal_poems[] = $entity->id();
    $month->save();
  }

  $current_user = \Drupal::currentUser();
  if ($current_user->isAnonymous()) {
    // Create or load the user based on the email and set the user as
    // the owner of this journal_poem.
    $email = $entity->field_email1->value;
    $user_storage = \Drupal::entityTypeManager()->getStorage('user');
    $users = $email
      ? $user_storage->loadByProperties(['mail' => $email])
      : [];
    $user = NULL;
    if ($users) {
      $user = reset($users);
    }
    else {
      $langcode = \Drupal::languageManager()
        ->getCurrentLanguage()->getId();
      $user = $user_storage->create([
        'name' => $email,
        'mail' => $email,
        'preferred_langcode' => $langcode,
        'langcode' => $langcode,
        'piv_teacher_first_name' => $entity->piv_teacher_first_name->value,
        'piv_teacher_last_name' => $entity->piv_teacher_last_name->value,
        'roles' => ['student_poet'],
        'status' => 1,
      ]);
      $user->save();
    }
    $entity->setOwner($user)->save();
  }

}

/**
 * Implements hook_inline_entity_form_table_fields_alter().
 */
function piv_futureverse_inline_entity_form_table_fields_alter(array &$fields, array $context) {
  if ($context['parent_entity_type'] == 'journal_year' && $context['field_name'] == 'field_journal_months') {
    // Display date on inline table when editing a journal year.
    $fields['field_start_date'] = [
      'type' => 'field',
      'label' => t('Start Date'),
      'weight' => 10,
      'display_options' => [
        'type' => 'datetime_default',
        'settings' => [
          'format_type' => 'html_date',
        ],
      ],
    ];
    $fields['field_end_date'] = [
      'type' => 'field',
      'label' => t('End Date'),
      'weight' => 11,
      'display_options' => [
        'type' => 'datetime_default',
        'settings' => [
          'format_type' => 'html_date',
        ],
      ],
    ];
  }
}

/**
 * Implements hook_inline_entity_form_entity_form_alter().
 */
function piv_futureverse_inline_entity_form_entity_form_alter(array &$entity_form, FormStateInterface &$form_state) {
  if ($entity_form['#entity_type'] == 'journal_month') {
    $journal_month = $entity_form['#entity'];
    if (!$journal_month) {
      return;
    }

    if ($journal_month->isNew()) {
      return;
    }

    // Add links to send monthly prize winner notification.
    $key_value = \Drupal::keyValue('journal_month_notifications');
    $key = 'monthly_prize_winner_' . $journal_month->id();
    $value = $key_value->get($key, ['poems' => []]);
    $poems_already_sent = $value['poems'] ?? [];
    // There should be only one.
    $winner_poems = JournalHelper::getMonthlyPrizeWinner($journal_month);
    $winner_poem_ids = array_map(fn($jm) => $jm->id(), $winner_poems);
    $poems_to_send = array_diff($winner_poem_ids, $poems_already_sent);

    // Send/resend.
    $send_label = count($poems_already_sent)
      ? t('Resend monthly prize winner notification')
      : t('Send monthly prize winner notification');

    $entity_form['monthly_prize_winner'] = [
      '#type' => 'fieldset',
    ];

    $winner_labels = array_map(function ($poem) {
      return "{$poem->label()} ({$poem->field_email1->value})";
    }, $winner_poems);
    $entity_form['monthly_prize_winner']['winner'] = [
      '#type' => 'item',
      '#markup' => t('Winner: @winner', [
        '@winner' => $winner_labels ? implode(', ', $winner_labels) : t('none'),
      ]),
    ];
    $entity_form['monthly_prize_winner']['send_notifications'] = [
      '#type' => 'link',
      '#title' => $send_label,
      '#url' => Url::fromRoute('piv_futureverse.journal_notifications_confirm', [
        'op' => 'monthly_prize_winner:send',
        'journal_month' => $journal_month->id(),
      ]),
      '#attributes' => [
        'class' => ['button'],
      ],
    ];
    if (count($poems_already_sent) && count($poems_to_send)) {
      // Update only send the ones that are missing if there are any.
      $entity_form['monthly_prize_winner']['update_notifications'] = [
        '#type' => 'link',
        '#title' => t('Update monthly prize winner notification'),
        '#url' => Url::fromRoute('piv_futureverse.journal_notifications_confirm', [
          'op' => 'monthly_prize_winner:update',
          'journal_month' => $journal_month->id(),
        ]),
        '#attributes' => [
          'class' => ['button'],
        ],
      ];
    }
  }
}
