<?php

/**
 * @file
 * Primary module hooks for PIV Constest module.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_entity_type_alter().
 */
function piv_contest_entity_type_alter(array &$entity_types) {
  if (!empty($entity_types['paragraph'])) {
    $entity_types['paragraph']->addConstraint('stream_constraint');
  }
}

/**
 * Implements hook_theme().
 */
function piv_contest_theme() {
  return [
    'recitation_score_form_default' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Implements template_preprocess_HOOK().
 */
function template_preprocess_recitation_score_form_default(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['form'][$key] = $variables['elements'][$key];
  }
}
