<?php

/**
 * @file
 * Primary module hooks for PIV Pathauto module.
 */

use Drupal\pathauto\PathautoPatternInterface;

/**
 * Implements hook_pathauto_pattern_alter().
 */
function piv_pathauto_pathauto_pattern_alter(PathautoPatternInterface $pattern, array $context) {
  if ($context['module'] == 'user' && !empty($context['data']['user'])) {
    $user = $context['data']['user'];
    if ($user->hasRole('poet')) {
      if ($user->getPreferredLangcode() == 'fr') {
        $pattern->setPattern('lire/poetes/[user:piv_teacher_first_name]-[user:piv_teacher_last_name]');
      }
      else {
        $pattern->setPattern('read/poets/[user:piv_teacher_first_name]-[user:piv_teacher_last_name]');
      }
    }
  }
}
