<?php

/**
 * @file
 * Provides a recitation entity type.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Render\Element;
use Drupal\piv_contest_recitation\Entity\Recitation;

/**
 * Implements hook_theme().
 */
function piv_contest_recitation_theme() {
  return [
    'recitation' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for recitation templates.
 *
 * Default template: recitation.html.twig.
 */
function template_preprocess_recitation(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_inline_entity_form_table_fields_alter().
 */
function piv_contest_recitation_inline_entity_form_table_fields_alter(array &$fields, array $context) {
  if ($context['entity_type'] === 'recitation') {
    $fields['label'] = [
      'type' => 'callback',
      'label' => t('Poem'),
      'callback' => 'piv_contest_recitation_inline_entity_form_title_callback',
    ];
    $fields['language'] = [
      'type' => 'callback',
      'label' => t('Language'),
      'callback' => 'piv_contest_recitation_inline_entity_form_language_callback',
    ];
  }
}

/**
 * Custom callback.
 */
function piv_contest_recitation_inline_entity_form_language_callback(Recitation $entity) {
  return $entity->language()->getName();
}

/**
 * Custom callback.
 */
function piv_contest_recitation_inline_entity_form_title_callback(Recitation $entity) {
  /** @var \Drupal\node\Entity\Node $poem */
  $poem = $entity->field_poem->entity;
  if ($poem) {
    return $poem->getTitle();
  }

  return "";
}

/**
 * Implements hook_entity_presave().
 */
function piv_contest_recitation_recitation_presave(EntityInterface $entity) {
  if (!$entity->getTitle() && $entity->field_poem->entity) {
    $entity->setTitle($entity->field_poem->entity->getTitle());
  }
}
