<?php

/**
 * @file
 * Primary module hooks for PIV User module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function piv_user_form_user_admin_settings_alter(&$form, FormStateInterface $form_state) {
  $form['registration_cancellation']['user_register']['#prefix'] = t('<b class="warning">Account registration is managed by piv_user in the /create-account route.</b>');
  $form['registration_cancellation']['user_register']['#disabled'] = TRUE;
}
