<?php

/**
 * @file
 * Primary module hooks for PIV User module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Drupal\Core\Link;
use Drupal\Core\Messenger\Messenger;

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Alter the user registration form for poets.
 */
function piv_user_form_user_poet_network_form_alter(&$form, FormStateInterface $form_state) {
  $user = $form_state->getFormObject()->getEntity();
  if (!$user->isNew()) {
    return;
  }

  $form['actions']['submit']['#submit'][] = 'piv_user_form_user_poet_network_form_custom_submit';
}

/**
 * Custom submit for poet creation form.
 */
function piv_user_form_user_poet_network_form_custom_submit(&$form, FormStateInterface $form_state) {
  $user = $form_state->getFormObject()->getEntity();
  $user->addRole('poet_network');
  $user->save();
  \Drupal::messenger()->deleteByType(Messenger::TYPE_STATUS);
  \Drupal::messenger()->addStatus(t('Thank you very much for applying for a Poet Network account. We will review your application and contact you soon. -The Poetry In Voice Team.'));

  $langcode = \Drupal::languageManager()->getCurrentLanguage()->getId();
  $replacements_service = \Drupal::service('piv_mail.replacements_service');
  $replacements_service->addSource('user', $user);
  piv_mail_send_mail('poet_applied_admin', $langcode, $replacements_service);

  // Do not redirect.
  $form_state->disableRedirect();
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Alter the user registration form for teachers.
 */
function piv_user_form_user_teacher_edit_form_alter(&$form, FormStateInterface $form_state) {
  $user = $form_state->getFormObject()->getEntity();
  if (!$user->isNew()) {
    return;
  }

  $form['actions']['submit']['#submit'][] = 'piv_user_form_user_teacher_edit_form_custom_submit';

  // Value will be set on submit for value = 1.
  $form['field_school']['widget'][0]['target_id']['#states'] = [
    'required' => [
      [
        [':input[name="field_canadian_educator_"]' => ['value' => 0]],
        'or',
        [':input[name="field_canadian_educator_"]' => ['value' => 2]],
      ],
    ],
    'invisible' => [
      [':input[name="field_canadian_educator_"]' => ['value' => 1]],
    ],
  ];
}

/**
 * Custom form submit.
 *
 * Handles roles, redirects and messages.
 *
 * @see Drupal\user\RegisterForm::submitForm()
 */
function piv_user_form_user_teacher_edit_form_custom_submit(&$form, FormStateInterface $form_state) {
  $user = $form_state->getFormObject()->getEntity();

  $need_save = FALSE;
  switch ($user->field_canadian_educator_->value) {
    // "I work at a canadian school".
    case 0:
      $user->activate()
        ->addRole('teacher');
      $need_save = TRUE;
      break;

    // "I am in Canada but am not affiliated with a school".
    case 1:
      $user->activate()
        ->addRole('teacher');
      $user->field_school = ['target_id' => 22469];
      $need_save = TRUE;
      break;

    // "I work outside of Canada".
    case 2:
      $user->activate()
        ->addRole('non_canadian_educator');
      $need_save = TRUE;
      break;

  }

  if ($need_save) {
    $user->save();
  }

  $url = Url::fromUri('mailto://webmaster@poetryinvoice.com');
  $link = Link::fromTextAndUrl('webmaster@poetryinvoice.com', $url);

  \Drupal::messenger()->deleteByType(Messenger::TYPE_STATUS);
  \Drupal::messenger()->addStatus(t('Thank you @display_name, we have sent you an email with a link to login. If you do not receive the email, please check your spam folder. Then, if needed, write to us at @email', [
    '@display_name' => $user->getDisplayName(),
    '@email' => $link->toString(),
  ]));

  $form_state->setRedirect('user.login');
}
