<?php

/**
 * @file
 * Primary module hooks for PIV Base module.
 */

use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Url;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Component\Utility\UrlHelper;
use Drupal\Core\Render\Markup;

/**
 * Implements hook_user_format_name_alter().
 */
function piv_base_user_format_name_alter(&$name, AccountInterface $account) {
  if ($account->isAuthenticated()) {
    $user = \Drupal::entityTypeManager()->getStorage('user')->load($account->id());
    if ($user) {
      $first_name = $user->piv_teacher_first_name->value;
      $last_name = $user->piv_teacher_last_name->value;
      if ($first_name || $last_name) {
        $name = trim("$first_name $last_name");
      }
    }
  }
}

/**
 * Implements hook_entity_form_mode_alter().
 */
function piv_base_entity_form_mode_alter(&$form_mode, EntityInterface $entity) {
  // Change the poet school visit form nodes if they are created by a teacher
  // that is not an admin.
  if ($entity->getEntityTypeId() == 'node' && $entity->bundle() == 'pal_pir_school_visit') {
    $current_user = \Drupal::currentUser();
    $roles = $current_user->getRoles();
    if ($current_user->id() != 1
    && !in_array('superadmin', $roles)
    && in_array('teacher', $roles)) {
      $form_mode = 'teacher';
    }
  }
  if ($entity->getEntityTypeId() == 'user') {
    $current_user = \Drupal::currentUser();
    if (!$current_user->hasPermission('administer site configuration')) {
      if ($entity->hasRole('teacher')) {
        $form_mode = 'teacher_edit';
      }
      elseif ($entity->hasRole('poet_network')) {
        $form_mode = 'poet_network';
      }
      // Else, just go with default.
    }
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function piv_base_preprocess_menu_local_tasks(&$variables) {
  $current_user = $variables['user'];
  $route = \Drupal::routeMatch();
  if ($route->getRouteName() == 'entity.node.edit_form') {
    $node = $route->getParameter('node');
    if ($node->bundle() == 'pal_pir_school_visit') {
      $roles = $current_user->getRoles();
      if ($current_user->id() != 1
      && !in_array('superadmin', $roles)
      && in_array('teacher', $roles)) {
        // Disable secondary menu on poet visit school node if user is not
        // admin.
        unset($variables['secondary']['form_mode_manager.entities:form_mode_manager.node.teacher.task_tab']);
        if (count($variables['secondary']) == 1) {
          $variables['secondary'] = [];
        }
      }
    }
    return;
  }

  // Disable form modes for users if not admin.
  if (!$current_user->hasPermission('administer site configuration')) {
    unset($variables['primary']['form_mode_manager.entities:form_mode_manager.user.poet_network.task_tab']);
    unset($variables['primary']['form_mode_manager.entities:form_mode_manager.user.poets.task_tab']);
    unset($variables['primary']['form_mode_manager.entities:form_mode_manager.user.teacher_edit.task_tab']);
  }
}

/**
 * Implements hook_form_alter().
 */
function piv_base_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (in_array($form_id, [
    'paragraph_poet_questionnaire_form',
    'paragraph_teacher_questionnaire_form',
  ])) {
    $form['actions']['submit']['#submit'][] = 'piv_base_form_survey_custom_submit';
  }

  if (in_array($form_id, [
    'node_pal_pir_school_visit_form',
    'node_pal_pir_school_visit_edit_form',
  ])) {
    $current_user = \Drupal::currentUser();
    $roles = $current_user->getRoles();
    if ($current_user->id() != 1 && !in_array('superadmin', $roles)) {
      $form['langcode']['#access'] = FALSE;
    }

    $form_display = $form_state->getStorage()['form_display'];
    if ($form_display && $form_display->getMode() == 'teacher') {
      $form['field_preferred_poet_s_']['#states'] = [
        'visible' => [
          ':input[name="field_do_you_have_any_poet_prefe[value]"]' => ['checked' => TRUE],
        ],
      ];
      $form['field_date_and_start_time']['#states'] = [
        'visible' => [
          ':input[name="field_preferred_date[value]"]' => ['checked' => TRUE],
        ],
      ];
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function piv_base_node_presave(EntityInterface $entity) {
  if ($entity->bundle() == 'pal_pir_school_visit') {
    // Title is the node created time or current time in case of new node.
    $entity->title = $entity->created->value ?? \Drupal::time()->getCurrentTime();
  }
}

/**
 * Implements hook_entity_create_access().
 */
function piv_base_entity_create_access(AccountInterface $account, array $context, $entity_bundle) {
  // Prevent teachers with no schools from creating school visits.
  $entity_type_id = $context['entity_type_id'] ?? NULL;
  if ($entity_type_id == 'node' && $entity_bundle == 'pal_pir_school_visit') {
    $user = \Drupal::entityTypeManager()->getStorage('user')->load($account->id());
    $school_can_create_visit = $user->field_school->entity->field_allow_poet_visits_school->value == 1;
    if (!$user || !$school_can_create_visit) {
      return AccessResult::forbidden();
    }
  }

  return AccessResult::neutral();
}

/**
 * Implements hook_theme().
 */
function piv_base_theme($existing, $type, $theme, $path) {
  return [
    'piv_welcome_modal' => [
      'render element' => 'content',
      'variables' => [
        'menu' => NULL,
        'form' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_page().
 */
function piv_base_preprocess_html(&$variables) {
  $langcode = \Drupal::languageManager()->getCurrentLanguage()->getId();
  $variables['langcode'] = $langcode;

  $route = \Drupal::routeMatch();
  if ($route->getRouteName() == 'entity.node.canonical') {
    if ($node = $route->getParameter('node')) {
      // If there is no translation for the current node to the current site
      // language, redirect the user to the original node language url.
      if (!$node->hasTranslation($langcode)) {
        $default_language = $node->language();
        // Non-system language.
        if (!$default_language->isLocked()) {
          $url = $node->toUrl();
          $url->setOption('language', $default_language);
          $response = new RedirectResponse($url->toString());
          $response->send();
          return;
        }
      }
    }
  }

  if (!\Drupal::service('router.admin_context')->isAdminRoute()) {
    $entity_type_manager = \Drupal::entityTypeManager();
    $block = $entity_type_manager->getStorage('block')->load('useraccountmenu');
    $variables['page_bottom'][] = [
      '#theme' => 'piv_welcome_modal',
      '#menu' => $entity_type_manager->getViewBuilder('block')->view($block),
      '#form' => \Drupal::formBuilder()->getForm('\Drupal\piv_base\Form\PivWelcomeModal'),
    ];
  }
}

/**
 * Custom submit handler for paragraph surveys.
 */
function piv_base_form_survey_custom_submit($form, FormStateInterface $form_state) {
  $paragraph = $form_state->getFormObject()->getEntity();
  $node = $form_state->get('survey_paragraph_node') ?? $paragraph->getParentEntity();
  // If editing a paragraph that exists, the field_name will be empty. It is not
  // a problem since the node already references the paragraph.
  $field_name = $form_state->get('survey_paragraph_field');
  if ($node && $field_name && $paragraph) {
    $node->{$field_name} = $paragraph;
    $node->save();
  }
  if ($paragraph->bundle() == 'poet_questionnaire') {
    $form_state->setRedirect('piv_base.poet_survey_view', [
      'node' => $node->id(),
    ]);
  }
  elseif ($paragraph->bundle() == 'teacher_questionnaire') {
    $form_state->setRedirect('piv_base.teacher_survey_view', [
      'node' => $node->id(),
    ]);
  }

  \Drupal::messenger()->addMessage(t('The changes have been saved.'));
}

/**
 * Implements hook_preprocess_HOOK().
 */
function piv_base_preprocess_links__language_block(&$variables) {
  $route = \Drupal::routeMatch();
  $route_name = $route->getRouteName();
  if ($route_name == 'entity.node.canonical') {
    // If there is no translation, the language switcher should redirect the
    // user to the frontpage.
    if ($node = $route->getParameter('node')) {
      foreach ($variables['links'] as $langcode => &$link) {
        if (!$node->hasTranslation($langcode)) {
          // Language is already set in the link options.
          $link['link']['#url'] = Url::fromRoute('<front>');
        }
      }
    }
  }
  // Unset the links for the current language.
  $langcode = \Drupal::languageManager()->getCurrentLanguage()->getId();
  unset($variables['links'][$langcode]);
}

/**
 * Implements hook_page_attachments_alter().
 */
function piv_base_page_attachments_alter(array &$attachments) {
  if (\Drupal::service('router.admin_context')->isAdminRoute()) {
    // Do not alter favicon for admin routes.
    return;
  }

  global $base_path;
  $langcode = \Drupal::languageManager()->getCurrentLanguage()->getId();
  $theme = \Drupal::theme()->getActiveTheme();
  $favicon = "{$base_path}{$theme->getPath()}/favicon-{$langcode}.ico";

  // Alter favicon to use translatable favicons.
  // Mimetype is hardcoded and will work for .ico, needs to be changed if
  // replaced by png or others.
  $attachments['#attached']['html_head_link'] = [];
  $attachments['#attached']['html_head_link'][][] = [
    'rel' => 'icon',
    'href' => UrlHelper::stripDangerousProtocols($favicon),
    'type' => 'image/vnd.microsoft.icon',
  ];
}

/**
 * Implements hook_preprocess_node().
 */
function piv_base_preprocess_node(&$variables) {
  // Add a print button to all node types.
  global $base_path;
  $path = \Drupal::service('extension.list.module')->getPath('piv_base');
  $image_path = "{$base_path}{$path}/assets/print_icon.gif";
  $markup = Markup::create("<img src='{$image_path}' onclick='window.print()' class='print-icon' style='cursor: pointer;'>");
  $variables['print_button'] = [
    '#markup' => $markup,
  ];
}
